import axios from 'axios';
import FormData from 'form-data';
import { image as nvidiaImage } from '../../lib/nvidia.js';
import { getBotName } from '../../lib/botname.js';
import { getOwnerName, getFooter } from '../../lib/menuHelper.js';

const CASPER_URL      = 'https://ai-image-gen.xcasper.space/v1/image/prompt/generate';
const CASPER_BING_URL = 'https://ai-image-gen.xcasper.space/v1/image/bing/generate';

// ── Primary: NVIDIA-hosted FLUX.1-dev ───────────────────────────
async function generateNvidiaFlux(prompt) {
  return nvidiaImage(prompt, {
    model:    'black-forest-labs/flux.1-dev',
    width:    1024,
    height:   1024,
    steps:    30,
    cfgScale: 3.5,
    timeoutMs: 90000
  });   // returns Buffer
}

// ── Fallback 1: xcasper hosted Flux ─────────────────────────────
async function generateCasper(prompt, size = '1024x1024') {
  const form = new FormData();
  form.append('prompt', prompt);
  form.append('total_images', '1');
  form.append('image_size', size);
  const res = await axios.post(CASPER_URL, form, {
    headers: form.getHeaders(), timeout: 50000
  });
  if (res.data?.error) throw new Error(res.data.error);
  if (!res.data?.url?.[0]) throw new Error('No image returned');
  return res.data.url[0];   // returns URL
}

// ── Magic Studio (Bing engine) — kept for `flux magic …` ────────
async function generateMagic(prompt) {
  const form = new FormData();
  form.append('prompt', prompt);
  form.append('total_images', '1');
  const res = await axios.post(CASPER_BING_URL, form, {
    headers: form.getHeaders(), timeout: 60000
  });
  if (res.data?.error) throw new Error(res.data.error);
  if (!res.data?.url?.[0]) throw new Error('No image returned');
  return res.data.url[0];
}

// ── Last-ditch fallback: pollinations.ai ────────────────────────
function pollinationsUrl(prompt) {
  return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&model=flux&seed=${Date.now()}`;
}

export default {
  name: 'flux',
  aliases: ['fluxai', 'imageai', 'aiimage'],
  category: 'ai',
  description: 'Generate an AI image — primary engine: NVIDIA FLUX.1-dev',

  async execute(sock, m, args, PREFIX) {
    const jid = m.key.remoteJid;

    if (!args.length) {
      return sock.sendMessage(jid, {
        text:
          `╭─⌈ 🎨 *FLUX AI IMAGE GEN* ⌋\n` +
          `├─⊷ *${PREFIX}flux <prompt>*\n` +
          `│  └⊷ NVIDIA FLUX.1-dev (with auto-fallback)\n` +
          `├─⊷ *${PREFIX}flux magic <prompt>*\n` +
          `│  └⊷ Magic Studio (Bing) engine\n` +
          `╰⊷ ${getFooter(m.key.participant || m.key.remoteJid)}`
      }, { quoted: m });
    }

    const useMagic = args[0]?.toLowerCase() === 'magic';
    const prompt   = useMagic ? args.slice(1).join(' ') : args.join(' ');

    if (!prompt.trim()) {
      return sock.sendMessage(jid, {
        text: `❌ Please provide a prompt after *${PREFIX}flux*`
      }, { quoted: m });
    }

    try {
      await sock.sendMessage(jid, { react: { text: '🎨', key: m.key } });

      let buffer  = null;
      let engine  = '';

      if (useMagic) {
        // Magic mode -> Bing engine
        const url = await generateMagic(prompt);
        const r   = await axios.get(url, { responseType: 'arraybuffer', timeout: 30000 });
        buffer    = Buffer.from(r.data);
        engine    = 'Magic Studio';
      } else {
        // 1) NVIDIA FLUX.1-dev (direct buffer)
        try {
          buffer = await generateNvidiaFlux(prompt);
          engine = 'NVIDIA FLUX.1-dev';
        } catch (e1) {
          console.error('[FLUX] NVIDIA failed:', e1.message);

          // 2) xcasper fallback (URL -> buffer)
          try {
            const url = await generateCasper(prompt);
            const r   = await axios.get(url, { responseType: 'arraybuffer', timeout: 30000 });
            buffer    = Buffer.from(r.data);
            engine    = 'xCasper Flux';
          } catch (e2) {
            console.error('[FLUX] xCasper failed:', e2.message);

            // 3) pollinations.ai fallback
            const url = pollinationsUrl(prompt);
            const r   = await axios.get(url, { responseType: 'arraybuffer', timeout: 30000 });
            buffer    = Buffer.from(r.data);
            engine    = 'Pollinations';
          }
        }
      }

      if (!buffer || buffer.length === 0) throw new Error('No image data received from any engine');

      await sock.sendMessage(jid, {
        image:   buffer,
        caption:
          `🎨 *AI Generated Image*\n` +
          `📝 _${prompt}_\n` +
          `⚙️ Engine: ${engine}\n\n` +
          `_Generated by ${getBotName()}_`
      }, { quoted: m });

      await sock.sendMessage(jid, { react: { text: '✅', key: m.key } });

    } catch (err) {
      console.error('[FLUX] All engines failed:', err.message);
      await sock.sendMessage(jid, { react: { text: '❌', key: m.key } });
      await sock.sendMessage(jid, {
        text: `❌ *Image generation failed*\n\n${err.message}\n\n💡 Try a shorter or different prompt.`
      }, { quoted: m });
    }
  }
};
