import { getBotName } from '../../lib/botname.js';
import { createRequire } from 'module';
import { tmpdir } from 'os';
import { join } from 'path';
import { createWriteStream, readFileSync, unlinkSync, existsSync } from 'fs';

const require = createRequire(import.meta.url);

export default {
    name: 'topdf',
    alias: ['text2pdf', 'txt2pdf', 'maketopdf'],
    description: 'Convert text to a PDF document',
    category: 'utility',

    async execute(sock, m, args, PREFIX) {
        const chatId = m.key.remoteJid;

        const contextInfo = m.message?.extendedTextMessage?.contextInfo;
        const quotedText  = contextInfo?.quotedMessage?.conversation
                         || contextInfo?.quotedMessage?.extendedTextMessage?.text;

        const inputText = args.join(' ').trim() || quotedText?.trim();

        if (!inputText) {
            return sock.sendMessage(chatId, {
                text: `╭⊷『 📄 TEXT TO PDF 』\n│\n` +
                      `├⊷ *Usage:*\n` +
                      `├⊷ ${PREFIX}topdf <your text here>\n` +
                      `│   — OR —\n` +
                      `├⊷ Reply to a text message with ${PREFIX}topdf\n` +
                      `│\n` +
                      `├⊷ *Examples:*\n` +
                      `├⊷ ${PREFIX}topdf Hello World\n` +
                      `└⊷ ${PREFIX}topdf My name is Wolf and I love coding.\n\n` +
                      `╰⊷ *${getBotName()} Utility* 🐾`
            }, { quoted: m });
        }

        await sock.sendMessage(chatId, { react: { text: '⏳', key: m.key } });

        const outPath = join(tmpdir(), `wolfbot_pdf_${Date.now()}.pdf`);

        try {
            const PDFDocument = require('pdfkit');

            await new Promise((resolve, reject) => {
                const doc    = new PDFDocument({ margin: 50, size: 'A4' });
                const stream = createWriteStream(outPath);

                doc.pipe(stream);

                doc.fontSize(13)
                   .font('Helvetica-Bold')
                   .fillColor('#1a1a2e')
                   .text(`Generated by ${getBotName()}`, { align: 'center' });

                doc.moveDown(0.4);
                doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
                doc.moveDown(0.8);

                doc.fontSize(12)
                   .font('Helvetica')
                   .fillColor('#000000')
                   .text(inputText, {
                       align: 'left',
                       lineGap: 4,
                       paragraphGap: 6,
                       width: 495
                   });

                doc.moveDown(1.5);
                doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
                doc.moveDown(0.4);

                doc.fontSize(9)
                   .fillColor('#888888')
                   .text(`Created on ${new Date().toUTCString()}`, { align: 'center' });

                doc.end();
                stream.on('finish', resolve);
                stream.on('error', reject);
            });

            const pdfBuffer = readFileSync(outPath);
            const wordCount = inputText.split(/\s+/).length;
            const charCount = inputText.length;

            await sock.sendMessage(chatId, { react: { text: '✅', key: m.key } });
            await sock.sendMessage(chatId, {
                document: pdfBuffer,
                mimetype: 'application/pdf',
                fileName: `${getBotName()}_${Date.now()}.pdf`,
                caption: `╭⊷『 📄 PDF READY 』\n│\n` +
                         `├⊷ *Words:* ${wordCount}\n` +
                         `├⊷ *Chars:* ${charCount}\n` +
                         `├⊷ *Size:* ${(pdfBuffer.length / 1024).toFixed(1)} KB\n` +
                         `╰⊷ *${getBotName()} Utility* 🐾`
            }, { quoted: m });

        } catch (err) {
            await sock.sendMessage(chatId, { react: { text: '❌', key: m.key } });
            await sock.sendMessage(chatId, {
                text: `╭⊷『 📄 TEXT TO PDF 』\n│\n` +
                      `├⊷ *Error:* ${err.message}\n` +
                      `└⊷ Please try again\n\n` +
                      `╰⊷ *${getBotName()} Utility* 🐾`
            }, { quoted: m });
        } finally {
            if (existsSync(outPath)) unlinkSync(outPath);
        }
    }
};
